<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Global.asax">
      <SubType>Component</SubType>
    </Content>
    <Content Include="Index.html" />
    <Content Include="themes.less" />
    <Content Include="themes.css.map">
      <DependentUpon>themes.css</DependentUpon>
    </Content>
    <Content Include="Content\Themes\blueTheme.less" />
    <None Include="Web.Debug.config">
      <DependentUpon>Web.config</DependentUpon>
    </None>
    <None Include="Web.Release.config">
      <DependentUpon>Web.config</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="themes.css">
      <DependentUpon>themes.less</DependentUpon>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\dotless.Namedthemes\dotless.Core.NamedThemes.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="dotless" Version="1.6.7" />
    <PackageReference Include="dotless.AspNetHandler" Version="1.6.7" />
    <PackageReference Include="dotless.Core" Version="1.6.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
  </ItemGroup>
</Project>