<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <RestorePackages>true</RestorePackages>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>dotless.Core.NamedThemes</AssemblyTitle>
    <Description>Named themes plugin for dotless upgraded from Steve Cooper%27s repo</Description>
    <Company>Kyle Levien</Company>
    <Product>dotless.Core.NamedThemes</Product>
    <Copyright>MIT License</Copyright>
    <AssemblyVersion>2.0.0</AssemblyVersion>
    <!-- NuGet package metadata -->
    <PackageId>dotless.Core.NamedThemes</PackageId>
    <Version>2.0.1</Version>
    <Authors>Kyle Levien</Authors>
    <PackageProjectUrl>https://github.com/tehkyle/dotless.NamedThemes</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>dotless less css themes</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Title>Named Themes for dotless</Title>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="dotless.Core" Version="1.6.7" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.7" />
    <PackageReference Include="System.Runtime.Caching" Version="10.0.7" />
  </ItemGroup>
</Project>
